### ISSUE TITLE
token service does not skip ssl validation

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/go-pivnet#27]
This [HTTP client](https://github.com/pivotal-cf/go-pivnet/blob/e82f75e026c76d31a3056410facf49cf37657e2a/uaa.go#L25) is just the default HTTP client.

There is no option to disable SkipSSLValidation here.

**Comment by rszumlakowski** [comment]
I'll raise a bug in our Tracker to look into this issue.  Thank you for reporting it @jtarchie .

**Comment by pivotal-kahin-ng** [comment]
Fix in place in this commit: 7ce0bc6ba7876274e630722a5def9f421eb832b5

Closing issue.
