### ISSUE TITLE
Public method ReleasesService.List() changed its API without a major semver bump

### ISSUE THREAD

**Issue by coro** [pivotal-cf/go-pivnet#32]
FYI: https://github.com/pivotal-cf/kiln/issues/36

Kiln uses [an interface](https://github.com/pivotal-cf/kiln/blob/fec14b6980d4549be184ac1baa84ae8c712aada6/commands/publish.go#L30-L33) which is implemented by the type `ReleaseService` in this repo. This interface matches the function signature of the `List()` method of this type.

In the commit 19ab81bdc63c7b1f5eb3701d3e06e617d1bcf5db in this repo, a breaking change was introduced to the function signature of this method, which added a new parameter to the `List()` method. This was not accompanied with a bump to the major version of this library, so the kiln code consuming this library picked up the change and began failing to compile.

Since this is a public method, the API to the method shouldn't really change without the major version bump. Please could you revert this change and either introduce the change in a new v3 of the library, or create a different public method for running `List()` with query params? Thanks!

**Comment by rszumlakowski** [comment]
This issue has been fixed in v2.0.11 of go-pivnet.
