### ISSUE TITLE
Large response bodies can cause out of memory

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf/go-pivnet#4]
see https://github.com/pivotal-cf/pivnet-resource/issues/46

it seems [this line](https://github.com/pivotal-cf/go-pivnet/blob/master/pivnet.go#L205) might be causing out of memory issues when the response body is large, for example when downloading releases.

**Comment by davewalter** [comment]
Just to clarify, this is on the implicit get step following a put, not on the put itself. We have seen it consistently (3 out of 3) in the last 24 hours with our 1.9 ERT, which is a little over 7G right now, compared to around 4.5G for the 1.6, 1.7 anhd 1.8 ERTs.

**Comment by robdimsdale** [comment]
@zachgersh @davewalter can you confirm the recent changes to the `develop` branch have resolved this issue?

**Comment by zachgersh** [comment]
Looks green to me - so it seems to have successfully downloaded / uploaded.

**Comment by robdimsdale** [comment]
Great - this is now fixed on https://github.com/pivotal-cf/pivnet-resource/releases/tag/v0.27.2
